<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>AchievementHunter.Api</RootNamespace>
    </PropertyGroup>


    <ItemGroup>
        <ProjectReference Include="..\AchievementHunter.Infrastructure\AchievementHunter.Infrastructure.csproj" />
    </ItemGroup>


    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10"/>
    </ItemGroup>

</Project>
